# Generated by Django 2.1.15 on 2021-02-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='نام')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='مشخصات')),
            ],
            options={
                'verbose_name': 'قطعه',
                'verbose_name_plural': 'قطعات',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='نام')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='مشخصات')),
                ('input', models.ManyToManyField(blank=True, null=True, to='app.Material', verbose_name=' قطعه ')),
            ],
            options={
                'verbose_name': 'ایستگاه',
                'verbose_name_plural': 'ایستگاه ها',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': ' محصول ', 'verbose_name_plural': ' محصولات '},
        ),
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='product',
            name='input',
            field=models.ManyToManyField(blank=True, null=True, to='app.Material', verbose_name=' قطعه '),
        ),
    ]
