# Generated by Django 2.1.15 on 2021-02-20 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210220_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='input',
        ),
        migrations.RemoveField(
            model_name='station',
            name='input',
        ),
    ]
