# Generated by Django 2.1.15 on 2021-02-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='input',
            field=models.ManyToManyField(related_name='_material_input_+', to='app.Material'),
        ),
        migrations.AddField(
            model_name='material',
            name='input2',
            field=models.ManyToManyField(to='app.Station'),
        ),
    ]
