# Generated by Django 2.1.15 on 2021-02-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210220_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='input',
        ),
        migrations.RemoveField(
            model_name='material',
            name='input2',
        ),
        migrations.AddField(
            model_name='material',
            name='material_input',
            field=models.ManyToManyField(blank=True, null=True, related_name='_material_material_input_+', to='app.Material', verbose_name=' قطعه ورودی'),
        ),
        migrations.AddField(
            model_name='material',
            name='station_input',
            field=models.ManyToManyField(blank=True, null=True, to='app.Station', verbose_name=' ایستگاه ورودی '),
        ),
        migrations.AddField(
            model_name='product',
            name='material_input',
            field=models.ManyToManyField(blank=True, null=True, to='app.Material', verbose_name=' قطعه ورودی'),
        ),
        migrations.AddField(
            model_name='product',
            name='station_input',
            field=models.ManyToManyField(blank=True, null=True, to='app.Station', verbose_name=' ایستگاه ورودی '),
        ),
        migrations.AddField(
            model_name='station',
            name='material_input',
            field=models.ManyToManyField(blank=True, null=True, to='app.Material', verbose_name=' قطعه ورودی'),
        ),
        migrations.AddField(
            model_name='station',
            name='station_input',
            field=models.ManyToManyField(blank=True, null=True, related_name='_station_station_input_+', to='app.Station', verbose_name=' ایستگاه ورودی '),
        ),
    ]
