# Generated by Django 2.1.15 on 2021-02-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210220_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='input',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='output',
        ),
        migrations.AlterField(
            model_name='material',
            name='material_input',
            field=models.ManyToManyField(blank=True, related_name='_material_material_input_+', to='app.Material', verbose_name=' قطعه ورودی'),
        ),
        migrations.AlterField(
            model_name='material',
            name='station_input',
            field=models.ManyToManyField(blank=True, to='app.Station', verbose_name=' ایستگاه ورودی '),
        ),
        migrations.AlterField(
            model_name='product',
            name='material_input',
            field=models.ManyToManyField(blank=True, to='app.Material', verbose_name=' قطعه ورودی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='station_input',
            field=models.ManyToManyField(blank=True, to='app.Station', verbose_name=' ایستگاه ورودی '),
        ),
        migrations.AlterField(
            model_name='station',
            name='material_input',
            field=models.ManyToManyField(blank=True, to='app.Material', verbose_name=' قطعه ورودی'),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_input',
            field=models.ManyToManyField(blank=True, related_name='_station_station_input_+', to='app.Station', verbose_name=' ایستگاه ورودی '),
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
