# Generated by Django 2.1.15 on 2021-02-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210220_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='station_input',
            new_name='s_sub',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='material_input',
            new_name='m_sub',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='station_input',
            new_name='s_sub',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='material_input',
            new_name='m_sub',
        ),
        migrations.RemoveField(
            model_name='material',
            name='material_input',
        ),
        migrations.RemoveField(
            model_name='station',
            name='station_input',
        ),
        migrations.AddField(
            model_name='material',
            name='m_sub',
            field=models.ManyToManyField(blank=True, related_name='_material_m_sub_+', to='app.Material', verbose_name=' قطعه ورودی'),
        ),
        migrations.AddField(
            model_name='station',
            name='s_sub',
            field=models.ManyToManyField(blank=True, related_name='_station_s_sub_+', to='app.Station', verbose_name=' ایستگاه ورودی '),
        ),
        migrations.AlterField(
            model_name='material',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
